# Generated by Django 4.2.18 on 2025-02-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0002_remove_faq_language_faq_answer_bn_faq_answer_hi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='language_code',
            field=models.CharField(default='en', max_length=5),
        ),
    ]
